project_name: kubectl-daemons
builds:
  - binary: kubectl-d
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
      - netbsd
      - openbsd
      - freebsd
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    ldflags: -s -w -X main.version={{.Version}}
archives:
  - format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
